### ISSUE TITLE
support for arrays and/or csv-formatted strings for batch-add of params

### ISSUE THREAD

**Issue by henkisdabro** [mbaersch/url-cleaner#3]
Hi again, and once again thanks for your great tool, making great use of it!

I've been working away at a [collection of clickid parameters](https://github.com/cremedigital/platform-url-click-id-parameters) that I've scoured from the web over a few years of running campaigns and filtering params from GA reports accordingly. This is what led me to your tool, which I found to be one of the best ones of the lot! I was wondering if there was a way to add support for providing an array and/or csv-string of multiple parameters, rather than having to create and manage individual lines for every parameter within your template. 

Idea:  a checkbox to select whether the user wants to
1. input parameters into individual lines as it's currently being presented
2. input all parameters as a csv-string or array into an empty text-field
3. reference another GTM variable as input for params. 
4. fetch from github repo or other URL - fetch a list of params dynamically from github (via jsdelivr or similar)?

Again thanks for your great tool, feel free to provide any thoughts on my list there too should you have any!

**Comment by mbaersch** [comment]
Hi

csv strings in one row seems like a good idea; I added this option to template.tpl of the beta branch. You can import https://github.com/mbaersch/url-cleaner/blob/beta/template.tpl and overwrite the existing template in order to test that - just add "param1, param2, param3" in one single list item and it should work. 

using variable values there is possible at any time so there is no need to change anything. 

loading lists from external ressources? No - seems like overkill to me. If you want to achieve that, build a variable template or Custom JS var that pulls the values in as a comma separated list from elsewhere and use this as input for the list item.

**Comment by henkisdabro** [comment]
Excellent, thanks for the quick turnaround! Personally I love the solution, I tested and it works as expected even when using regex characters too. Yes I see the lego-brick symbol there too yes, to reference another GTM variable, was already possible indeed! Thanks for the tip with importing via a variable template or custom js variable, I'll explore those options too!

**Comment by mbaersch** [comment]
Importing external data in a template might be a problem for a client side template. Server templates can provide all that is required to get values by loading a file or querying an API

In the browser, the best way seems to provide the information already in the dataLayer (CMS must handle this) when a page loads. Otherwise you will have to use JS in order to load data, persist it in a cookie or somewhere and add an event to the dataLayer so you can wait until the exclusion data is finally available. Not very elegant, I guess. And you might run into CORS issues as well. 

If you want to give it a try, something like this might work for you: 

```
var xhr;
xhr = new XMLHttpRequest();
xhr.onreadystatechange = push2dataLayer;
xhr.open("GET", "https://raw.githubusercontent.com/cremedigital/platform-url-click-id-parameters/main/parameter_commaseparated.csv", true);
xhr.send();

function push2dataLayer() {
    if ((xhr.readyState === 4) && (xhr.status == 200)) {
        window.dataLayer = window.dataLayer || [];
        window.dataLayer.push({event: "blacklistReady", "paramsBlacklist": xhr.response});
    }
}

```

You can use the event to trigger all tags that have to use the `paramsBlacklist` value from the dataLayer

**Comment by mbaersch** [comment]
FYI: added option to gallery template, should be appear as update in GTM soon. You can then "resync" your teplate with the gallery using the "restore template" button in the template editor.

**Comment by mbaersch** [comment]
Done

**Comment by henkisdabro** [comment]
> Importing external data in a template might be a problem for a client side template. Server templates can provide all that is required to get values by loading a file or querying an API
> 
> In the browser, the best way seems to provide the information already in the dataLayer (CMS must handle this) when a page loads. Otherwise you will have to use JS in order to load data, persist it in a cookie or somewhere and add an event to the dataLayer so you can wait until the exclusion data is finally available. Not very elegant, I guess. And you might run into CORS issues as well.
> 
> If you want to give it a try, something like this might work for you:
> 
> ```
> var xhr;
> xhr = new XMLHttpRequest();
> xhr.onreadystatechange = push2dataLayer;
> xhr.open("GET", "https://raw.githubusercontent.com/cremedigital/platform-url-click-id-parameters/main/parameter_commaseparated.csv", true);
> xhr.send();
> 
> function push2dataLayer() {
>     if ((xhr.readyState === 4) && (xhr.status == 200)) {
>         window.dataLayer = window.dataLayer || [];
>         window.dataLayer.push({event: "blacklistReady", "paramsBlacklist": xhr.response});
>     }
> }
> ```
> 
> You can use the event to trigger all tags that have to use the `paramsBlacklist` value from the dataLayer

Really appreciate providing a solution here and taking the time to explain the pros/cons, much appreciated!
